# Generated by Django 2.1.4 on 2018-12-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnAir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updDate', models.DateTimeField(auto_now_add=True, verbose_name='활성 일시')),
            ],
        ),
        migrations.CreateModel(
            name='XbmcMediaHost',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='XBMC호스트')),
                ('ipaddress', models.CharField(max_length=50, verbose_name='IP주소')),
                ('macaddress', models.CharField(max_length=17, verbose_name='MAC주소')),
                ('osinfo', models.CharField(max_length=200, verbose_name='운영체제정보')),
                ('appinfo', models.CharField(max_length=200, verbose_name='XBMC정보')),
                ('deviceinfo', models.CharField(max_length=200, verbose_name='장치정보')),
            ],
        ),
        migrations.AddField(
            model_name='onair',
            name='xmbcmediahost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xbmccontrolroom.XbmcMediaHost', verbose_name='XBMC호스트'),
        ),
    ]
