# Generated by Django 2.0.7 on 2019-01-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbmccontrolroom', '0005_auto_20181226_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onair',
            name='action',
            field=models.CharField(choices=[('downloadAndPlay', '다운로드 및 플레이'), ('quit', '호스트종료'), ('restart', '호스트재시작'), ('reboot', '리부트'), ('powerdown', '전원끄기')], default='', max_length=64, verbose_name='동작 명령'),
        ),
    ]
