# Generated by Django 2.1.4 on 2019-01-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xbmccontrolroom', '0008_addonfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addonfile',
            options={'verbose_name': 'Addon File', 'verbose_name_plural': 'Addon File'},
        ),
    ]
