# Generated by Django 2.1.5 on 2019-02-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbmccontrolroom', '0011_auto_20190104_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='idx',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='식별자'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='md5',
            field=models.CharField(max_length=255, verbose_name='MD5 해시'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.IntegerField(choices=[(0, '일반'), (1, '썸네일용')], default=0, help_text='0 일반, 1 썸네일', verbose_name='썸네일용'),
        ),
        migrations.AlterField(
            model_name='xbmcmediahost',
            name='idx',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='식별자'),
        ),
    ]
