# Generated by Django 2.1.5 on 2019-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbmccontrolroom', '0012_auto_20190208_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.CharField(max_length=255, null=True, verbose_name='태그'),
        ),
    ]
