# Generated by Django 2.1.5 on 2019-06-20 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('xbmccontrolroom', '0014_auto_20190521_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBoard',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='식별자')),
                ('name', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('md5', models.CharField(max_length=255, verbose_name='MD5 해시')),
                ('updDate', models.DateTimeField(auto_now_add=True, verbose_name='기록 일시')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('thumbnail_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboard_relation_thumbnail', to='xbmccontrolroom.MediaFile', verbose_name='썸네일')),
            ],
            options={
                'verbose_name': 'Story Board',
                'verbose_name_plural': 'Story Boards',
            },
        ),
        migrations.CreateModel(
            name='StoryNotepad',
            fields=[
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='내용')),
                ('updDate', models.DateTimeField(auto_now_add=True, verbose_name='기록 일시')),
            ],
            options={
                'verbose_name': 'Story Notepad',
                'verbose_name_plural': 'Story Notepads',
            },
        ),
        migrations.AlterModelOptions(
            name='addonfile',
            options={'verbose_name': 'Kodi Addon File', 'verbose_name_plural': 'Kodi Addon Files'},
        ),
    ]
