# Generated by Django 2.1.5 on 2019-06-21 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xbmccontrolroom', '0015_auto_20190620_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storynotepad',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
