# Generated by Django 2.1.5 on 2019-06-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbmccontrolroom', '0016_auto_20190621_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyboard',
            name='serv_file',
            field=models.BinaryField(null=True, verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='storyboard',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
    ]
