# Generated by Django 2.0.6 on 2018-07-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type_flag', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('attached_file', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdAccountBook',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='accountbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbook.HouseholdAccountBook'),
        ),
    ]
