# Generated by Django 2.0.7 on 2018-07-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('thumbnail_file', models.CharField(max_length=1000)),
                ('type_flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='paymentmethod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountbook.PaymentMethod'),
        ),
    ]
