# Generated by Django 2.0.7 on 2018-07-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0002_auto_20180716_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='thumbnail_file',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='images/paymentmethod'),
        ),
    ]
