# Generated by Django 2.0.7 on 2018-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0003_auto_20180716_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='attached_file',
            field=models.ImageField(blank=True, max_length=2000, upload_to='images/deal'),
        ),
    ]
