# Generated by Django 2.0.7 on 2018-07-20 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0004_auto_20180716_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='images/paymentmethod/'),
        ),
    ]
