# Generated by Django 2.0.7 on 2018-07-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0005_auto_20180720_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('maker', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='type_flag',
            field=models.IntegerField(choices=[(1, '수입'), (0, '지출')], default=0),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type_flag',
            field=models.IntegerField(choices=[(1, '사용중'), (0, '사용불가')], default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbook.Deal'),
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbook.Product'),
        ),
    ]
