# Generated by Django 2.0.7 on 2018-07-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0006_auto_20180725_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='unitprice',
            new_name='price',
        ),
    ]
