# Generated by Django 2.0.7 on 2018-07-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0008_product_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(choices=[(0, '소모품'), (1, '구성품')], default=0)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrelation_relation_master', to='accountbook.Product')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrelation_relation_slave', to='accountbook.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productrelation',
            unique_together={('master', 'slave')},
        ),
    ]
