# Generated by Django 2.0.7 on 2018-08-02 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0009_auto_20180726_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('type_flag', models.IntegerField(choices=[(0, '현금성'), (1, '현물')], default=0)),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='images/asset/')),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wealth',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('holdings', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wealth_relation_master', to='accountbook.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='attached_file',
            field=models.ImageField(blank=True, max_length=2000, upload_to='images/deal/'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 2, 12, 13, 54, 833866), verbose_name='date registered'),
        ),
        migrations.AddField(
            model_name='wealth',
            name='deal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accountbook.Deal'),
        ),
        migrations.AddField(
            model_name='spending',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_spending_deal', to='accountbook.Deal'),
        ),
        migrations.AddField(
            model_name='spending',
            name='wealth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_spending_wealth', to='accountbook.Wealth'),
        ),
        migrations.AlterUniqueTogether(
            name='spending',
            unique_together={('wealth', 'deal')},
        ),
    ]
