# Generated by Django 2.0.7 on 2018-08-02 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0010_auto_20180802_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 2, 13, 59, 59, 333119), verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='consumption',
            field=models.IntegerField(default=0, help_text='소모량'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='deal',
            field=models.ForeignKey(help_text='사용 거래', on_delete=django.db.models.deletion.CASCADE, related_name='spending_relation_deal', to='accountbook.Deal'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='wealth',
            field=models.ForeignKey(help_text='사용 재산', on_delete=django.db.models.deletion.CASCADE, related_name='spending_relation_wealth', to='accountbook.Wealth'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='amount',
            field=models.IntegerField(default=0, help_text='획득량'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wealth_relation_wealth', to='accountbook.Asset'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='획득 거래', on_delete=django.db.models.deletion.CASCADE, to='accountbook.Deal'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='holdings',
            field=models.IntegerField(default=0, help_text='보유량'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='price',
            field=models.IntegerField(default=0, help_text='획득 금액'),
        ),
    ]
