# Generated by Django 2.0.7 on 2018-08-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0011_auto_20180802_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='abbreviation',
            field=models.CharField(help_text='자산 약칭', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='자산 명칭', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_flag',
            field=models.IntegerField(choices=[(0, '현금성'), (1, '현물')], default=0, help_text='유형 구분'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='regDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='package',
            name='deal',
            field=models.ForeignKey(help_text='거래', on_delete=django.db.models.deletion.CASCADE, to='accountbook.Deal'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=1, help_text='금액'),
        ),
        migrations.AlterField(
            model_name='package',
            name='product',
            field=models.ForeignKey(help_text='제품', on_delete=django.db.models.deletion.CASCADE, to='accountbook.Product'),
        ),
        migrations.AlterField(
            model_name='package',
            name='quantity',
            field=models.IntegerField(default=1, help_text='수량'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='asset',
            field=models.ForeignKey(help_text='자산', on_delete=django.db.models.deletion.CASCADE, related_name='wealth_relation_wealth', to='accountbook.Asset'),
        ),
    ]
