# Generated by Django 2.0.7 on 2018-08-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0012_auto_20180802_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='deal',
            field=models.ForeignKey(help_text='사용 거래', on_delete=django.db.models.deletion.CASCADE, related_name='spending_relation_deal', to='accountbook.Deal', verbose_name='사용 거래'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='wealth',
            field=models.ForeignKey(help_text='사용 재산', on_delete=django.db.models.deletion.CASCADE, related_name='spending_relation_wealth', to='accountbook.Wealth', verbose_name='사용 재산'),
        ),
    ]
