# Generated by Django 2.0.7 on 2018-08-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0013_auto_20180802_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='abbreviation',
            field=models.CharField(max_length=10, verbose_name='자산 약칭'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='자산 명칭'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_flag',
            field=models.IntegerField(choices=[(0, '현금성'), (1, '현물')], default=0, verbose_name='유형 구분'),
        ),
        migrations.AlterField(
            model_name='package',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbook.Deal', verbose_name='거래'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=1, verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='package',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbook.Product', verbose_name='제품'),
        ),
        migrations.AlterField(
            model_name='package',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='consumption',
            field=models.IntegerField(default=0, verbose_name='소모량'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_relation_deal', to='accountbook.Deal', verbose_name='사용 거래'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='wealth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_relation_wealth', to='accountbook.Wealth', verbose_name='사용 재산'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='획득량'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wealth_relation_wealth', to='accountbook.Asset', verbose_name='자산'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='deal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accountbook.Deal', verbose_name='획득 거래'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='holdings',
            field=models.IntegerField(default=0, verbose_name='보유량'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='price',
            field=models.IntegerField(default=0, verbose_name='획득 금액'),
        ),
    ]
