# Generated by Django 2.0.7 on 2018-08-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0014_auto_20180802_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='images/asset/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='accountbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbook.HouseholdAccountBook', verbose_name='기입 장부'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='attached_file',
            field=models.ImageField(blank=True, help_text='영수증, 내역서 등', max_length=2000, upload_to='images/deal/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='paymentmethod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountbook.PaymentMethod', verbose_name='결제 수단'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='regDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='발생 일시'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(max_length=100, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='type_flag',
            field=models.IntegerField(choices=[(1, '수입'), (0, '지출')], default=0, verbose_name='지출 구분'),
        ),
        migrations.AlterField(
            model_name='householdaccountbook',
            name='name',
            field=models.CharField(max_length=50, verbose_name='장부 이름'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='명칭'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='images/paymentmethod/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type_flag',
            field=models.IntegerField(choices=[(1, '사용중'), (0, '사용불가')], default=1, help_text='1 사용, 0 미사용', verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50, verbose_name='분류'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.CharField(max_length=50, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='images/product/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='productrelation',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrelation_relation_main', to='accountbook.Product', verbose_name='상위'),
        ),
        migrations.AlterField(
            model_name='productrelation',
            name='relation',
            field=models.IntegerField(choices=[(0, '소모품'), (1, '구성품')], default=0, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='productrelation',
            name='subordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrelation_relation_subordinate', to='accountbook.Product', verbose_name='하위'),
        ),
    ]
