# Generated by Django 2.0.7 on 2018-08-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0015_auto_20180802_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='regDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 일시'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='지불 수단 명칭'),
        ),
    ]
