# Generated by Django 2.0.7 on 2018-08-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0016_auto_20180808_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wealth',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wealth_relation_asset', to='accountbook.Asset', verbose_name='자산'),
        ),
    ]
