# Generated by Django 2.0.7 on 2018-08-10 23:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0017_auto_20180810_2107'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='asset',
            managers=[
                ('wealthes', django.db.models.manager.Manager()),
            ],
        ),
    ]
