# Generated by Django 2.0.7 on 2018-08-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0018_auto_20180810_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wealth',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountbook.Deal', verbose_name='획득 거래'),
        ),
    ]
