# Generated by Django 2.1 on 2018-09-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0022_auto_20180821_2327'),
        ('accountbook', '0022_auto_20180821_1011'),
    ]

    operations = [
    ]
