# Generated by Django 2.0.7 on 2019-01-01 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xbmccontrolroom', '0006_auto_20190101_1113'),
        ('accountbook', '0024_auto_20181210_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('thumbnail_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xbmccontrolroom.MediaFile', verbose_name='썸네일')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
