# Generated by Django 2.0.7 on 2019-01-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xbmccontrolroom', '0006_auto_20190101_1113'),
        ('accountbook', '0025_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='medias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_relation_medias', to='xbmccontrolroom.MediaFile', verbose_name='관련 미디어 파일'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_relation_thumbnail', to='xbmccontrolroom.MediaFile', verbose_name='썸네일'),
        ),
    ]
