# Generated by Django 2.1.4 on 2019-01-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0026_auto_20190101_1117'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='asset',
            managers=[
            ],
        ),
    ]
