# Generated by Django 2.1.4 on 2019-01-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0027_auto_20190102_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountbook.Event', verbose_name='관련 이벤트'),
        ),
        migrations.AddField(
            model_name='event',
            name='ongoing',
            field=models.IntegerField(choices=[(0, '종료'), (1, '진행')], default=0, verbose_name='진행 여부'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountbook.Person', verbose_name='구성원'),
        ),
    ]
