# Generated by Django 2.1.5 on 2019-01-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0029_auto_20190103_2313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spending',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='spending',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='wealth',
        ),
        migrations.RemoveField(
            model_name='wealth',
            name='holdings',
        ),
        migrations.AlterField(
            model_name='wealth',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='wealth',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountbook.Deal', verbose_name='관련 거래'),
        ),
        migrations.DeleteModel(
            name='Spending',
        ),
    ]
