# Generated by Django 2.1.5 on 2019-01-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0030_auto_20190111_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_flag',
            field=models.IntegerField(choices=[(0, '정상'), (1, '부족'), (2, '카트')], default=0, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='regDate',
            field=models.DateTimeField(verbose_name='등록 일시'),
        ),
    ]
